// Manufacturing edition: bills of material, production orders, raw materials (MRP-lite), work centres.
import { useState } from "react";
import { G, Inp, Sel, Btn, Kpi, Modal, TblWrap, todayStr, validNum } from "../apt/AptCrm.jsx";
import { Card, Stat, Grid, Toolbar, Search, Pill, SPill, useTable, Bars, lastMonths, monthKey } from "./shared.jsx";
import { sbPost } from "../data/mockApi.js";
import { fmt } from "../lib/config.js";
import { openPrintable } from "../lib/invoiceDoc.js";
import { Layers, Hammer, Boxes, Cog } from "lucide-react";

const MO_FLOW = { Planned: "In Progress", "In Progress": "QC", QC: "Completed" };
const bomCost = (b, prodMap) => { const mat = b.components.reduce((s, c) => s + c.qty * (prodMap[c.product_id]?.tradePrice || 0), 0); const total = (mat + b.labour_cost + b.overhead_cost) * (1 + b.scrap_pct / 100); return { mat, total }; };

const BomsPage = ({ ctx }) => {
  const [rows, reload] = useTable("boms", [ctx.dataVersion]); const [view, setView] = useState(null); const [add, setAdd] = useState(false);
  const raw = ctx.products.filter(p => ctx.prodMap[p.id] && (p.category === "Raw Material")); const fin = ctx.products.filter(p => p.category !== "Raw Material");
  const [f, setF] = useState({ product_id: "", labour_cost: 800, overhead_cost: 500, scrap_pct: 2 }); const [comps, setComps] = useState([{ product_id: "", qty: 1 }]);
  const save = async () => { if (!f.product_id || comps.some(c => !c.product_id)) return ctx.notify("Select product and components", "err"); await sbPost("upsert", { table: "boms", prefix: "BOM", label: "BOM", row: { ...f, product_name: ctx.prodMap[f.product_id]?.name, output_qty: 1, labour_cost: +f.labour_cost, overhead_cost: +f.overhead_cost, scrap_pct: +f.scrap_pct, components: comps.map(c => ({ product_id: c.product_id, product_name: ctx.prodMap[c.product_id]?.name, qty: +c.qty })) } }); ctx.notify("✅ BOM saved"); setAdd(false); reload(); };
  return (
    <div>
      <Toolbar><div style={{ flex: 1 }} /><Btn sm onClick={() => setAdd(true)}>+ New BOM</Btn><Btn sm v="secondary" onClick={() => ctx.exportCsv("boms.csv", rows.map(b => ({ ...b, cost: Math.round(bomCost(b, ctx.prodMap).total) })), [["id", "BOM"], ["product_name", "Product"], ["cost", "Unit Cost"], ["labour_cost", "Labour"], ["overhead_cost", "Overhead"], ["scrap_pct", "Scrap %"]])}>⬇ Export</Btn></Toolbar>
      <Grid cols={4}><Stat l="Bills of Material" v={rows.length} /><Stat l="Avg Material Share" v={`${Math.round(rows.reduce((s, b) => { const c = bomCost(b, ctx.prodMap); return s + c.mat / Math.max(1, c.total); }, 0) / Math.max(1, rows.length) * 100)}%`} c={G.blue} /><Stat l="Avg Gross Margin" v={`${Math.round(rows.reduce((s, b) => { const c = bomCost(b, ctx.prodMap); const p = ctx.prodMap[b.product_id]?.tradePrice || 0; return s + (p ? (p - c.total) / p : 0); }, 0) / Math.max(1, rows.length) * 100)}%`} c={G.mid} /><Stat l="Negative Margin SKUs" v={rows.filter(b => (ctx.prodMap[b.product_id]?.tradePrice || 0) < bomCost(b, ctx.prodMap).total).length} c={G.red} /></Grid>
      <Card title="Bills of Material — cost roll-up"><TblWrap compact heads={["BOM", "Finished Product", "Components", "Material", "Labour", "Overhead", "Scrap", "Unit Cost", "Sell Price", "Margin", ""]} rows={rows.map(b => { const c = bomCost(b, ctx.prodMap); const p = ctx.prodMap[b.product_id]?.tradePrice || 0; const m = p ? (p - c.total) / p : 0; return [<b style={{ fontSize: 11, color: G.dark }}>{b.id}</b>, <span style={{ fontSize: 11, fontWeight: 600 }}>{b.product_name}</span>, <span style={{ fontSize: 11 }}>{b.components.length}</span>, <span style={{ fontSize: 11 }}>{fmt(c.mat)}</span>, <span style={{ fontSize: 11 }}>{fmt(b.labour_cost)}</span>, <span style={{ fontSize: 11 }}>{fmt(b.overhead_cost)}</span>, <span style={{ fontSize: 10 }}>{b.scrap_pct}%</span>, <b style={{ fontSize: 11 }}>{fmt(c.total)}</b>, <span style={{ fontSize: 11 }}>{fmt(p)}</span>, <b style={{ fontSize: 11, color: m < 0.1 ? G.red : m < 0.25 ? G.amber : G.mid }}>{(m * 100).toFixed(0)}%</b>, <Btn sm v="ghost" onClick={() => setView(b)}>View</Btn>]; })} /></Card>
      {view && <Modal title={`🧩 ${view.id} — ${view.product_name}`} onClose={() => setView(null)}><TblWrap compact heads={["Component", "Qty / unit", "Unit Cost", "Line Cost", "In Stock"]} rows={view.components.map(c => [<span style={{ fontSize: 11 }}>{c.product_name}</span>, <b style={{ fontSize: 11 }}>{c.qty} {ctx.prodMap[c.product_id] ? "kg/pc" : ""}</b>, <span style={{ fontSize: 11 }}>{fmt(ctx.prodMap[c.product_id]?.tradePrice)}</span>, <span style={{ fontSize: 11 }}>{fmt(c.qty * (ctx.prodMap[c.product_id]?.tradePrice || 0))}</span>, <span style={{ fontSize: 11, color: (ctx.prodMap[c.product_id]?.currentStock || 0) < c.qty * 50 ? G.red : G.mid }}>{ctx.prodMap[c.product_id]?.currentStock ?? "—"}</span>])} /><div style={{ marginTop: 12, fontSize: 12, display: "flex", flexDirection: "column", gap: 4 }}>{[["Material", bomCost(view, ctx.prodMap).mat], ["Labour", view.labour_cost], ["Overhead", view.overhead_cost], [`Scrap allowance ${view.scrap_pct}%`, bomCost(view, ctx.prodMap).total - bomCost(view, ctx.prodMap).mat - view.labour_cost - view.overhead_cost]].map(([k, v]) => <div key={k} style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: G.muted }}>{k}</span><b>{fmt(v)}</b></div>)}<div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, fontWeight: 800, borderTop: `2px solid ${G.pale}`, paddingTop: 6 }}><span>Unit cost</span><span>{fmt(bomCost(view, ctx.prodMap).total)}</span></div></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 12 }}><Btn v="secondary" onClick={() => openPrintable(`BOM ${view.id}`, `<p><b>${view.product_name}</b></p><table><tr><th>Component</th><th class="r">Qty</th><th class="r">Cost</th></tr>${view.components.map(c => `<tr><td>${c.product_name}</td><td class="r">${c.qty}</td><td class="r">${fmt(c.qty * (ctx.prodMap[c.product_id]?.tradePrice || 0))}</td></tr>`).join("")}<tr><td colspan="2"><b>Unit cost (incl. labour, overhead, scrap)</b></td><td class="r"><b>${fmt(bomCost(view, ctx.prodMap).total)}</b></td></tr></table>`)}>🖨 Print</Btn><Btn onClick={() => setView(null)}>Close</Btn></div></Modal>}
      {add && <Modal title="🧩 New Bill of Material" onClose={() => setAdd(false)} wide><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><div style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr", gap: 10 }}><Sel label="Finished Product" value={f.product_id} onChange={e => setF(p => ({ ...p, product_id: e.target.value }))}><option value="">— Select —</option>{fin.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Sel><Inp label="Labour / unit" type="number" value={f.labour_cost} onChange={e => setF(p => ({ ...p, labour_cost: e.target.value }))} /><Inp label="Overhead / unit" type="number" value={f.overhead_cost} onChange={e => setF(p => ({ ...p, overhead_cost: e.target.value }))} /><Inp label="Scrap %" type="number" value={f.scrap_pct} onChange={e => setF(p => ({ ...p, scrap_pct: e.target.value }))} /></div><div style={{ fontSize: 10, fontWeight: 800, color: G.muted, textTransform: "uppercase" }}>Components</div>{comps.map((c, i) => <div key={i} style={{ display: "grid", gridTemplateColumns: "3fr 1fr auto", gap: 8 }}><Sel value={c.product_id} onChange={e => setComps(p => p.map((x, j) => j === i ? { ...x, product_id: e.target.value } : x))}><option value="">— Raw material —</option>{raw.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Sel><Inp type="number" step="0.1" value={c.qty} onChange={e => setComps(p => p.map((x, j) => j === i ? { ...x, qty: e.target.value } : x))} /><button onClick={() => setComps(p => p.filter((_, j) => j !== i))} style={{ background: G.pink, border: "none", borderRadius: 7, padding: "8px 9px", cursor: "pointer", color: G.red, fontWeight: 800 }}>✕</button></div>)}<div><Btn sm v="ghost" onClick={() => setComps(p => [...p, { product_id: "", qty: 1 }])}>+ Component</Btn></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Save BOM</Btn></div></div></Modal>}
    </div>
  );
};

const ProductionPage = ({ ctx }) => {
  const [rows, reload] = useTable("production_orders", [ctx.dataVersion]); const [boms] = useTable("boms", [ctx.dataVersion]); const [wcs] = useTable("work_centers", [ctx.dataVersion]);
  const [st, setSt] = useState("All"); const [add, setAdd] = useState(false); const [f, setF] = useState({ bom_id: "", qty: 100, work_center: "", due: new Date(Date.now() + 5 * 864e5).toISOString().slice(0, 10), priority: "Normal" });
  const [finish, setFinish] = useState(null); const [scrap, setScrap] = useState(0);
  const fil = rows.filter(r => st === "All" || r.status === st);
  const save = async () => { const b = boms.find(x => x.id === f.bom_id); if (!b) return ctx.notify("Select a BOM", "err"); await sbPost("upsert", { table: "production_orders", prefix: "MO", label: "Production order", row: { ...f, qty: +f.qty, product_id: b.product_id, product_name: b.product_name, produced: 0, scrap: 0, start: todayStr(), status: "Planned", work_center: f.work_center || wcs[0]?.name } }); ctx.notify("✅ Production order planned"); setAdd(false); reload(); };
  const advance = async r => {
    const next = MO_FLOW[r.status]; if (!next) return;
    if (next === "Completed") { setFinish(r); return; }
    if (next === "In Progress") { const b = boms.find(x => x.id === r.bom_id); if (b) for (const c of b.components) await sbPost("adjust_stock", { pid: c.product_id, delta: -Math.round(c.qty * r.qty) }); ctx.notify("📦 Raw materials issued to the floor"); }
    await sbPost("upsert", { table: "production_orders", label: "Production order", row: { ...r, status: next, produced: next === "QC" ? r.qty : r.produced } }); ctx.notify(`✅ ${r.id} → ${next}`); reload(); ctx.loadData(true);
  };
  const complete = async () => { const r = finish; const good = r.qty - (+scrap || 0); await sbPost("adjust_stock", { pid: r.product_id, delta: good }); await sbPost("upsert", { table: "production_orders", label: "Production order", row: { ...r, status: "Completed", produced: good, scrap: +scrap || 0 } }); ctx.notify(`✅ ${r.id} completed · ${good} units to finished goods`); setFinish(null); setScrap(0); reload(); ctx.loadData(true); };
  const months = lastMonths(6);
  return (
    <div>
      <Toolbar>{["All", "Planned", "In Progress", "QC", "Completed"].map(s => <button key={s} onClick={() => setSt(s)} style={{ padding: "5px 11px", borderRadius: 20, border: `1.5px solid ${st === s ? G.dark : G.border}`, background: st === s ? G.dark : G.bg, color: st === s ? G.white : G.ink, fontSize: 10, fontWeight: 700, cursor: "pointer" }}>{s}</button>)}<div style={{ flex: 1 }} /><Btn sm onClick={() => setAdd(true)}>+ Plan Production</Btn><Btn sm v="secondary" onClick={() => ctx.exportCsv("production_orders.csv", rows, [["id", "MO"], ["product_name", "Product"], ["qty", "Qty"], ["produced", "Produced"], ["scrap", "Scrap"], ["work_center", "Work Centre"], ["start", "Start"], ["due", "Due"], ["status", "Status"]])}>⬇ Export</Btn></Toolbar>
      <Grid cols={4}><Stat l="On the Floor" v={rows.filter(r => r.status === "In Progress").length} c={G.blue} /><Stat l="Awaiting QC" v={rows.filter(r => r.status === "QC").length} c={G.purple} /><Stat l="Output (last 30 days)" v={rows.filter(r => r.status === "Completed" && r.start >= new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10)).reduce((s, r) => s + r.produced, 0).toLocaleString() + " units"} c={G.mid} /><Stat l="Scrap Rate" v={`${(rows.filter(r => r.status === "Completed").reduce((s, r) => s + r.scrap, 0) / Math.max(1, rows.filter(r => r.status === "Completed").reduce((s, r) => s + r.qty, 0)) * 100).toFixed(1)}%`} c={G.red} /></Grid>
      <Card title="Production Orders"><TblWrap compact heads={["MO", "Product", "Qty", "Produced", "Scrap", "Work Centre", "Start", "Due", "Priority", "Status", "Action"]} rows={fil.map(r => [<b style={{ fontSize: 11, color: G.dark }}>{r.id}</b>, <span style={{ fontSize: 11, fontWeight: 600 }}>{r.product_name}</span>, <span style={{ fontSize: 11 }}>{r.qty}</span>, <span style={{ fontSize: 11, color: G.mid }}>{r.produced}</span>, <span style={{ fontSize: 11, color: r.scrap ? G.red : G.muted }}>{r.scrap}</span>, <span style={{ fontSize: 10 }}>{r.work_center}</span>, <span style={{ fontSize: 10, color: G.muted }}>{r.start}</span>, <span style={{ fontSize: 10, fontWeight: 700, color: r.due < todayStr() && r.status !== "Completed" ? G.red : G.muted }}>{r.due}</span>, <Pill text={r.priority} color={r.priority === "High" ? G.red : G.muted} bg={r.priority === "High" ? G.pink : "#EEF2F3"} />, <SPill s={r.status} />, MO_FLOW[r.status] ? <Btn sm v="success" onClick={() => advance(r)}>→ {MO_FLOW[r.status]}</Btn> : <Btn sm v="ghost" onClick={() => openPrintable(`Job Card ${r.id}`, `<p><b>${r.product_name}</b> · Qty ${r.qty} · ${r.work_center}</p><p>Produced ${r.produced} · Scrap ${r.scrap}</p>`)}>Job Card</Btn>])} /></Card>
      <div style={{ marginTop: 14 }}><Card title="Monthly Output (units)" color={G.blue}><div style={{ padding: 16 }}><Bars series={[{ label: "Good units", color: G.mid, values: months.map(k => ({ k, v: rows.filter(r => r.status === "Completed" && monthKey(r.start) === k).reduce((s, r) => s + r.produced, 0) })) }, { label: "Scrap", color: G.red, values: months.map(k => ({ k, v: rows.filter(r => r.status === "Completed" && monthKey(r.start) === k).reduce((s, r) => s + r.scrap, 0) })) }]} /></div></Card></div>
      {add && <Modal title="🏭 Plan Production Order" onClose={() => setAdd(false)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><Sel label="Bill of Material" value={f.bom_id} onChange={e => setF(p => ({ ...p, bom_id: e.target.value }))}><option value="">— Select —</option>{boms.map(b => <option key={b.id} value={b.id}>{b.product_name}</option>)}</Sel><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Inp label="Quantity" type="number" value={f.qty} onChange={e => setF(p => ({ ...p, qty: e.target.value }))} /><Sel label="Work Centre" value={f.work_center} onChange={e => setF(p => ({ ...p, work_center: e.target.value }))}>{wcs.map(w => <option key={w.id}>{w.name}</option>)}</Sel><Inp label="Due" type="date" value={f.due} onChange={e => setF(p => ({ ...p, due: e.target.value }))} /><Sel label="Priority" value={f.priority} onChange={e => setF(p => ({ ...p, priority: e.target.value }))}>{["Low", "Normal", "High"].map(x => <option key={x}>{x}</option>)}</Sel></div>{f.bom_id && (() => { const b = boms.find(x => x.id === f.bom_id); const short = b.components.filter(c => (ctx.prodMap[c.product_id]?.currentStock || 0) < c.qty * (+f.qty || 0)); return <div style={{ background: short.length ? G.pink : G.pale, borderRadius: 8, padding: "8px 12px", fontSize: 11, fontWeight: 700, color: short.length ? G.red : G.mid }}>{short.length ? `⚠ Short on: ${short.map(c => c.product_name).join(", ")}` : "✓ Materials available for this run"} · est. cost {fmt(bomCost(b, ctx.prodMap).total * (+f.qty || 0))}</div>; })()}<div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Plan</Btn></div></div></Modal>}
      {finish && <Modal title={`✅ Complete ${finish.id}`} onClose={() => setFinish(null)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><div style={{ background: G.pale, borderRadius: 8, padding: 12, fontSize: 12 }}>{finish.product_name} · planned {finish.qty} units</div><Inp label="Scrap / rejected units" type="number" value={scrap} onChange={e => setScrap(e.target.value)} /><div style={{ fontSize: 12, fontWeight: 700, color: G.mid }}>{finish.qty - (+scrap || 0)} good units will be received into finished goods stock</div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><Btn v="secondary" onClick={() => setFinish(null)}>Cancel</Btn><Btn v="success" onClick={complete}>Complete & Receive</Btn></div></div></Modal>}
    </div>
  );
};

const RawMaterialsPage = ({ ctx }) => {
  const [mos] = useTable("production_orders", [ctx.dataVersion]); const [boms] = useTable("boms", [ctx.dataVersion]);
  const raw = ctx.inventory.filter(p => p.category === "Raw Material");
  const req = {}; mos.filter(m => m.status === "Planned").forEach(m => { const b = boms.find(x => x.id === m.bom_id); b?.components.forEach(c => { req[c.product_id] = (req[c.product_id] || 0) + c.qty * m.qty; }); });
  const rows = raw.map(p => ({ ...p, req: Math.round(req[p.pid] || 0), avail: p.stock - Math.round(req[p.pid] || 0) }));
  const po = async () => { const short = rows.filter(r => r.avail < r.minStock); if (!short.length) return ctx.notify("Nothing to reorder", "err"); const v = ctx.vendors[0]; const items = short.map(r => ({ product_id: r.pid, product_name: r.pname, qty: Math.max(r.minStock * 2, -r.avail + r.minStock), rate: r.cost, total: 0, notes: "" })); items.forEach(i => i.total = i.qty * i.rate); await sbPost("upsert_purchase", { purchase: { id: `PO-${Date.now()}`, date: todayStr(), vendor_id: v.id, total: items.reduce((s, i) => s + i.total, 0), notes: "Auto-generated from MRP shortage", status: "Ordered", items } }); ctx.notify(`🛒 Purchase order raised for ${short.length} materials`); ctx.loadData(true); };
  return (
    <div>
      <Toolbar><div style={{ flex: 1 }} /><Btn sm v="success" onClick={po}>🛒 Raise PO for shortages</Btn><Btn sm v="secondary" onClick={() => ctx.exportCsv("raw_materials.csv", rows, [["pid", "ID"], ["pname", "Material"], ["stock", "Stock"], ["req", "Required (planned)"], ["avail", "Available"], ["minStock", "Min"]])}>⬇ Export</Btn></Toolbar>
      <Grid cols={4}><Stat l="Raw Materials" v={raw.length} /><Stat l="Stock Value" v={fmt(raw.reduce((s, p) => s + p.stock * p.cost, 0))} c={G.blue} /><Stat l="Reserved for Planned MOs" v={fmt(rows.reduce((s, r) => s + r.req * r.cost, 0))} c={G.amber} /><Stat l="Shortages" v={rows.filter(r => r.avail < r.minStock).length} c={G.red} /></Grid>
      <Card title="Material Requirements (planned production vs stock)"><TblWrap compact heads={["Material", "Unit Cost", "In Stock", "Required (planned MOs)", "Available After", "Min", "Status", "Action"]} rows={rows.map(r => [<span style={{ fontSize: 11, fontWeight: 600 }}>{r.pname}</span>, <span style={{ fontSize: 11 }}>{fmt(r.cost)}</span>, <b style={{ fontSize: 11 }}>{r.stock.toLocaleString()}</b>, <span style={{ fontSize: 11, color: G.amber }}>{r.req.toLocaleString()}</span>, <b style={{ fontSize: 11, color: r.avail < 0 ? G.red : G.ink }}>{r.avail.toLocaleString()}</b>, <span style={{ fontSize: 10, color: G.muted }}>{r.minStock}</span>, r.avail < 0 ? <Pill text="Shortage" color={G.red} bg={G.pink} /> : r.avail < r.minStock ? <Pill text="Reorder" color={G.amber} bg="#FFF4E5" /> : <Pill text="OK" color={G.mid} bg={G.pale} />, <Btn sm v="ghost" onClick={() => ctx.setModal({ t: "adjustStock", d: r })}>± Adjust</Btn>])} /></Card>
    </div>
  );
};

const WorkCentersPage = ({ ctx }) => {
  const [wcs, reload] = useTable("work_centers", [ctx.dataVersion]); const [mos] = useTable("production_orders", [ctx.dataVersion]);
  const toggle = async w => { await sbPost("upsert", { table: "work_centers", label: "Work centre", row: { ...w, status: w.status === "Running" ? "Maintenance" : "Running" } }); reload(); };
  return (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 12 }}>
      {wcs.map(w => { const load = mos.filter(m => m.work_center === w.name && m.status !== "Completed"); const hrs = load.reduce((s, m) => s + m.qty * 0.05, 0); return <div key={w.id} style={{ background: G.card, borderRadius: 12, padding: 16, boxShadow: "0 2px 10px rgba(15,59,76,0.07)", borderTop: `4px solid ${w.status === "Running" ? G.mid : G.amber}` }}><div style={{ display: "flex", justifyContent: "space-between" }}><div style={{ fontWeight: 800, fontSize: 14 }}>{w.name}</div><SPill s={w.status} /></div><div style={{ fontSize: 10, color: G.muted, margin: "2px 0 10px" }}>{w.capacity_hrs}h/day capacity</div><div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: G.muted }}><span>Load (open MOs)</span><b>{hrs.toFixed(0)}h ≈ {(hrs / w.capacity_hrs).toFixed(1)} days</b></div><div style={{ height: 8, background: G.pale, borderRadius: 4, margin: "4px 0 10px" }}><div style={{ height: "100%", width: `${Math.min(100, hrs / (w.capacity_hrs * 5) * 100)}%`, background: hrs / (w.capacity_hrs * 5) > 0.9 ? G.red : G.mid, borderRadius: 4 }} /></div><div style={{ fontSize: 11, color: G.ink }}>{load.length} open order(s): {load.map(m => m.id).join(", ") || "—"}</div><div style={{ marginTop: 10 }}><Btn sm v={w.status === "Running" ? "amber" : "success"} onClick={() => toggle(w)}>{w.status === "Running" ? "🔧 Schedule maintenance" : "▶ Back to running"}</Btn></div></div>; })}
    </div>
  );
};

const DashboardExtra = ({ ctx }) => {
  const [mos] = useTable("production_orders", [ctx.dataVersion]); const [wcs] = useTable("work_centers", [ctx.dataVersion]);
  const done = mos.filter(m => m.status === "Completed"); const month = lastMonths(1)[0];
  return <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 12 }}><Kpi label="Orders on the Floor" value={mos.filter(m => m.status === "In Progress").length} sub={`${mos.filter(m => m.status === "QC").length} in QC`} color={G.blue} icon={Hammer} /><Kpi label="Output (30 days)" value={done.filter(m => m.start >= new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10)).reduce((s, m) => s + m.produced, 0).toLocaleString()} sub="good units" color={G.mid} icon={Layers} /><Kpi label="Scrap Rate" value={`${(done.reduce((s, m) => s + m.scrap, 0) / Math.max(1, done.reduce((s, m) => s + m.qty, 0)) * 100).toFixed(1)}%`} color={G.red} icon={Boxes} /><Kpi label="Lines Running" value={`${wcs.filter(w => w.status === "Running").length}/${wcs.length}`} color={G.purple} icon={Cog} /></div>;
};

export const MANUFACTURING = {
  navGroups: [{ group: "Production", items: [{ id: "boms", label: "Bills of Material" }, { id: "production", label: "Production Orders" }, { id: "raw-materials", label: "Raw Materials (MRP)" }, { id: "work-centers", label: "Work Centres" }] }],
  pages: { boms: BomsPage, production: ProductionPage, "raw-materials": RawMaterialsPage, "work-centers": WorkCentersPage },
  DashboardExtra,
};
