// Services edition: projects, timesheets, retainers, staff utilisation.
import { useState } from "react";
import { G, Inp, Sel, Btn, Kpi, Modal, TblWrap, todayStr, validNum } from "../apt/AptCrm.jsx";
import { Card, Stat, Grid, Toolbar, Search, Pill, SPill, useTable, Bars, lastMonths, monthKey } from "./shared.jsx";
import { sbPost } from "../data/mockApi.js";
import { fmt } from "../lib/config.js";
import { openPrintable } from "../lib/invoiceDoc.js";
import { FolderKanban, Timer, Repeat, Users } from "lucide-react";

const STAFF = ["Sara Khan", "Omer Siddiqui", "Hira Malik", "Zain Abbas", "Mahnoor Ali", "Daniyal Rauf"];
const nextInvId = ctx => `INV-${String(Math.max(1000, ...ctx.invoices.map(i => parseInt((i.id.match(/INV-(\d+)/) || [])[1] || 0))) + 1).padStart(4, "0")}`;

const ProjectsPage = ({ ctx }) => {
  const [rows, reload] = useTable("projects", [ctx.dataVersion]); const [ts] = useTable("timesheets", [ctx.dataVersion]);
  const [q, setQ] = useState(""); const [view, setView] = useState(null); const [add, setAdd] = useState(false);
  const [f, setF] = useState({ name: "", cust_id: "", manager: STAFF[0], budget: "", hours_est: "", due: new Date(Date.now() + 45 * 864e5).toISOString().slice(0, 10) });
  const fil = rows.filter(r => !q || `${r.name} ${r.cust_name} ${r.manager}`.toLowerCase().includes(q.toLowerCase()));
  const save = async () => { if (!f.name || !f.cust_id) return ctx.notify("Enter project name and client", "err"); await sbPost("upsert", { table: "projects", prefix: "PRJ", label: "Project", row: { ...f, cust_name: ctx.custMap[f.cust_id]?.name, budget: +f.budget || 0, hours_est: +f.hours_est || 0, billed: 0, hours_logged: 0, start: todayStr(), status: "Planning", progress: 0 } }); ctx.notify("✅ Project created"); setAdd(false); reload(); };
  const setStatus = async (r, status) => { await sbPost("upsert", { table: "projects", label: "Project", row: { ...r, status, progress: status === "Completed" ? 100 : r.progress } }); reload(); setView(null); };
  const billMilestone = async r => { const amt = Math.round(r.budget * 0.25); const id = nextInvId(ctx); await sbPost("upsert_invoice", { invoice: { id, date: todayStr(), cust_id: r.cust_id, cust_name: r.cust_name, total: amt, status: "Unpaid", pay_terms: "NET 15", created_by: ctx.user.email, notes: `Milestone — ${r.name}`, items: [{ product_id: "", product_name: `${r.name} — milestone billing (25%)`, qty: 1, rate: amt, total: amt, notes: "" }] } }); await sbPost("upsert", { table: "projects", label: "Project", row: { ...r, billed: r.billed + amt } }); ctx.notify(`🧾 ${id} raised for ${fmt(amt)}`); await ctx.loadData(true); reload(); setView(null); };
  const active = rows.filter(r => r.status === "In Progress");
  return (
    <div>
      <Toolbar><Search value={q} onChange={setQ} placeholder="Search projects…" /><Btn sm onClick={() => setAdd(true)}>+ New Project</Btn><Btn sm v="secondary" onClick={() => ctx.exportCsv("projects.csv", rows, [["id", "ID"], ["name", "Project"], ["cust_name", "Client"], ["manager", "Manager"], ["budget", "Budget"], ["billed", "Billed"], ["hours_logged", "Hours"], ["status", "Status"], ["due", "Due"]])}>⬇ Export</Btn></Toolbar>
      <Grid cols={4}><Stat l="Active Projects" v={active.length} c={G.blue} /><Stat l="Contracted Value" v={fmt(rows.filter(r => r.status !== "Completed").reduce((s, r) => s + r.budget, 0))} c={G.mid} /><Stat l="Unbilled Budget" v={fmt(rows.reduce((s, r) => s + Math.max(0, r.budget - r.billed), 0))} c={G.amber} /><Stat l="Overdue" v={rows.filter(r => r.status !== "Completed" && r.due < todayStr()).length} c={G.red} /></Grid>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(300px,1fr))", gap: 12 }}>
        {fil.map(r => { const over = r.hours_logged > r.hours_est; return <div key={r.id} onClick={() => setView(r)} style={{ background: G.card, borderRadius: 12, padding: 16, boxShadow: "0 2px 10px rgba(15,59,76,0.07)", cursor: "pointer", borderTop: `3px solid ${r.status === "Completed" ? G.mid : r.status === "On Hold" ? G.amber : G.blue}` }}>
          <div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><div><div style={{ fontWeight: 800, fontSize: 13 }}>{r.name}</div><div style={{ fontSize: 10, color: G.muted }}>{r.cust_name} · PM {r.manager}</div></div><SPill s={r.status} /></div>
          <div style={{ margin: "10px 0 4px", display: "flex", justifyContent: "space-between", fontSize: 10, color: G.muted }}><span>Progress</span><b>{r.progress}%</b></div><div style={{ height: 7, background: G.pale, borderRadius: 4 }}><div style={{ height: "100%", width: `${r.progress}%`, background: G.mid, borderRadius: 4 }} /></div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 6, marginTop: 10 }}>{[["Budget", fmt(r.budget)], ["Billed", fmt(r.billed)], ["Hours", `${r.hours_logged}/${r.hours_est}`]].map(([l, v], i) => <div key={l} style={{ background: G.pale, borderRadius: 6, padding: "6px 5px", textAlign: "center" }}><div style={{ fontSize: 10, fontWeight: 700, color: i === 2 && over ? G.red : G.dark }}>{v}</div><div style={{ fontSize: 8, color: G.muted }}>{l}</div></div>)}</div>
          <div style={{ fontSize: 10, color: r.due < todayStr() && r.status !== "Completed" ? G.red : G.muted, marginTop: 8 }}>Due {r.due}</div>
        </div>; })}
      </div>
      {view && <Modal title={`📁 ${view.name}`} onClose={() => setView(null)} wide>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8, marginBottom: 12 }}>{[["Client", view.cust_name], ["Manager", view.manager], ["Budget", fmt(view.budget)], ["Billed", fmt(view.billed)], ["Hours est.", view.hours_est], ["Hours logged", view.hours_logged], ["Start", view.start], ["Due", view.due]].map(([k, v]) => <div key={k} style={{ background: G.pale, borderRadius: 7, padding: "8px 11px" }}><div style={{ fontSize: 8, fontWeight: 700, color: G.muted, textTransform: "uppercase" }}>{k}</div><div style={{ fontSize: 12, fontWeight: 600 }}>{v}</div></div>)}</div>
        <Card title="Recent time entries" color={G.mid}><TblWrap compact heads={["Date", "Staff", "Task", "Hours", "Billable"]} rows={ts.filter(t => t.project_id === view.id).slice(0, 12).map(t => [<span style={{ fontSize: 10, color: G.muted }}>{t.date}</span>, <span style={{ fontSize: 11 }}>{t.staff}</span>, <span style={{ fontSize: 11 }}>{t.task}</span>, <b style={{ fontSize: 11 }}>{t.hours}h</b>, <span style={{ fontSize: 11 }}>{t.billable ? "✓" : "—"}</span>])} /></Card>
        <div style={{ display: "flex", justifyContent: "space-between", marginTop: 12, flexWrap: "wrap", gap: 8 }}><div style={{ display: "flex", gap: 8 }}>{view.status === "Planning" && <Btn v="secondary" onClick={() => setStatus(view, "In Progress")}>▶ Start</Btn>}{view.status === "In Progress" && <Btn v="secondary" onClick={() => setStatus(view, "On Hold")}>⏸ Hold</Btn>}{view.status === "On Hold" && <Btn v="secondary" onClick={() => setStatus(view, "In Progress")}>▶ Resume</Btn>}{view.status !== "Completed" && <Btn v="success" onClick={() => setStatus(view, "Completed")}>✓ Complete</Btn>}</div><div style={{ display: "flex", gap: 8 }}>{view.billed < view.budget && <Btn onClick={() => billMilestone(view)}>🧾 Bill 25% Milestone</Btn>}<Btn v="secondary" onClick={() => setView(null)}>Close</Btn></div></div>
      </Modal>}
      {add && <Modal title="📁 New Project" onClose={() => setAdd(false)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><Inp label="Project Name" value={f.name} onChange={e => setF(p => ({ ...p, name: e.target.value }))} /><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Sel label="Client" value={f.cust_id} onChange={e => setF(p => ({ ...p, cust_id: e.target.value }))}><option value="">— Select —</option>{ctx.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Sel><Sel label="Project Manager" value={f.manager} onChange={e => setF(p => ({ ...p, manager: e.target.value }))}>{STAFF.map(s => <option key={s}>{s}</option>)}</Sel><Inp label="Budget" type="number" value={f.budget} onChange={e => setF(p => ({ ...p, budget: e.target.value }))} /><Inp label="Estimated Hours" type="number" value={f.hours_est} onChange={e => setF(p => ({ ...p, hours_est: e.target.value }))} /><Inp label="Due Date" type="date" value={f.due} onChange={e => setF(p => ({ ...p, due: e.target.value }))} /></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Create</Btn></div></div></Modal>}
    </div>
  );
};

const TimesheetsPage = ({ ctx }) => {
  const [rows, reload] = useTable("timesheets", [ctx.dataVersion]); const [projects, reloadP] = useTable("projects", [ctx.dataVersion]);
  const [f, setF] = useState({ date: todayStr(), staff: STAFF[0], project_id: "", hours: 4, task: "Development", billable: true, rate: 3500 });
  const [who, setWho] = useState("All");
  const fil = rows.filter(r => who === "All" || r.staff === who).sort((a, b) => b.date.localeCompare(a.date));
  const unbilled = rows.filter(r => r.billable && !r.invoiced);
  const log = async () => { if (!f.project_id || !validNum(f.hours) || +f.hours <= 0) return ctx.notify("Pick a project and hours", "err"); const p = projects.find(x => x.id === f.project_id); await sbPost("upsert", { table: "timesheets", prefix: "TS", label: "Timesheet", row: { ...f, hours: +f.hours, rate: +f.rate, project_name: p?.name } }); await sbPost("upsert", { table: "projects", label: "Project", row: { ...p, hours_logged: p.hours_logged + +f.hours } }); ctx.notify("✅ Time logged"); reload(); reloadP(); };
  const bill = async () => {
    const byClient = {}; unbilled.forEach(t => { const p = projects.find(x => x.id === t.project_id); if (!p) return; (byClient[p.cust_id] = byClient[p.cust_id] || { name: p.cust_name, items: [] }).items.push(t); });
    let n = 0; let seq = Math.max(1000, ...ctx.invoices.map(i => parseInt((i.id.match(/INV-(\d+)/) || [])[1] || 0)));
    for (const [cid, g] of Object.entries(byClient)) { const id = `INV-${String(++seq).padStart(4, "0")}`; const items = g.items.map(t => ({ product_id: "", product_name: `${t.project_name} — ${t.task} (${t.staff}, ${t.date})`, qty: t.hours, rate: t.rate, total: t.hours * t.rate, notes: "" })); await sbPost("upsert_invoice", { invoice: { id, date: todayStr(), cust_id: cid, cust_name: g.name, total: items.reduce((s, i) => s + i.total, 0), status: "Unpaid", pay_terms: "NET 15", created_by: ctx.user.email, notes: "Time & materials billing", items } }); for (const t of g.items) await sbPost("upsert", { table: "timesheets", label: "Timesheet", row: { ...t, invoiced: id } }); n++; }
    ctx.notify(`🧾 ${n} time & materials invoice(s) raised`); await ctx.loadData(true); reload();
  };
  const weekly = STAFF.map(s => { const w = rows.filter(r => r.staff === s && r.date >= new Date(Date.now() - 7 * 864e5).toISOString().slice(0, 10)); return { s, h: w.reduce((a, r) => a + r.hours, 0), b: w.filter(r => r.billable).reduce((a, r) => a + r.hours, 0) }; });
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <Card title="Log Time" color={G.mid}><div style={{ padding: 14, display: "grid", gridTemplateColumns: "1fr 1.2fr 1.6fr 0.7fr 1fr 0.8fr auto", gap: 8, alignItems: "end" }}><Inp label="Date" type="date" value={f.date} onChange={e => setF(p => ({ ...p, date: e.target.value }))} /><Sel label="Staff" value={f.staff} onChange={e => setF(p => ({ ...p, staff: e.target.value }))}>{STAFF.map(s => <option key={s}>{s}</option>)}</Sel><Sel label="Project" value={f.project_id} onChange={e => setF(p => ({ ...p, project_id: e.target.value }))}><option value="">— Select —</option>{projects.filter(p => p.status !== "Completed").map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Sel><Inp label="Hours" type="number" step="0.5" value={f.hours} onChange={e => setF(p => ({ ...p, hours: e.target.value }))} /><Sel label="Task" value={f.task} onChange={e => setF(p => ({ ...p, task: e.target.value }))}>{["Development", "Design", "Client call", "QA", "Reporting", "Research", "Support tickets", "Admin"].map(t => <option key={t}>{t}</option>)}</Sel><Sel label="Billable" value={f.billable ? "yes" : "no"} onChange={e => setF(p => ({ ...p, billable: e.target.value === "yes" }))}><option value="yes">Yes</option><option value="no">No</option></Sel><Btn onClick={log}>+ Log</Btn></div></Card>
      <Grid cols={4} mb={0}><Stat l="Unbilled Hours" v={unbilled.reduce((s, r) => s + r.hours, 0)} c={G.amber} sub={fmt(unbilled.reduce((s, r) => s + r.hours * r.rate, 0)) + " billable value"} /><Stat l="Hours This Week" v={weekly.reduce((s, w) => s + w.h, 0)} c={G.blue} /><Stat l="Billable Ratio" v={`${Math.round(rows.filter(r => r.billable).length / Math.max(1, rows.length) * 100)}%`} c={G.mid} /><Stat l="Entries" v={rows.length} /></Grid>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1.6fr", gap: 14 }}>
        <Card title="This Week by Staff" color={G.blue}><TblWrap compact heads={["Staff", "Hours", "Billable", "Util."]} rows={weekly.map(w => [<span style={{ fontSize: 11, fontWeight: 600 }}>{w.s}</span>, <b style={{ fontSize: 11 }}>{w.h}h</b>, <span style={{ fontSize: 11, color: G.mid }}>{w.b}h</span>, <span style={{ fontSize: 10, fontWeight: 700, color: w.h / 40 > 0.9 ? G.red : G.muted }}>{Math.round(w.h / 40 * 100)}%</span>])} /></Card>
        <Card title="Time Entries" right={<div style={{ display: "flex", gap: 6 }}><Sel value={who} onChange={e => setWho(e.target.value)} style={{ width: 150 }}><option>All</option>{STAFF.map(s => <option key={s}>{s}</option>)}</Sel><Btn sm v="success" disabled={!unbilled.length} onClick={bill}>🧾 Bill {unbilled.reduce((s, r) => s + r.hours, 0)}h unbilled</Btn></div>}><TblWrap compact heads={["Date", "Staff", "Project", "Task", "Hours", "Rate", "Billable", "Invoice"]} rows={fil.slice(0, 80).map(t => [<span style={{ fontSize: 10, color: G.muted }}>{t.date}</span>, <span style={{ fontSize: 11 }}>{t.staff}</span>, <span style={{ fontSize: 10 }}>{t.project_name}</span>, <Pill text={t.task} />, <b style={{ fontSize: 11 }}>{t.hours}h</b>, <span style={{ fontSize: 10 }}>{fmt(t.rate)}</span>, <span style={{ fontSize: 11, color: t.billable ? G.mid : G.muted }}>{t.billable ? "✓" : "—"}</span>, <span style={{ fontSize: 10, color: G.blue }}>{t.invoiced || (t.billable ? "unbilled" : "")}</span>])} /></Card>
      </div>
    </div>
  );
};

const RetainersPage = ({ ctx }) => {
  const [rows, reload] = useTable("retainers", [ctx.dataVersion]); const [add, setAdd] = useState(false);
  const [f, setF] = useState({ cust_id: "", service: "SEO Retainer", monthly_fee: "", hours_included: 20 });
  const mrr = rows.filter(r => r.status === "Active").reduce((s, r) => s + r.monthly_fee, 0);
  const due = rows.filter(r => r.status === "Active" && r.next_invoice <= new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 10));
  const generate = async () => { let seq = Math.max(1000, ...ctx.invoices.map(i => parseInt((i.id.match(/INV-(\d+)/) || [])[1] || 0))); for (const r of due) { const id = `INV-${String(++seq).padStart(4, "0")}`; await sbPost("upsert_invoice", { invoice: { id, date: todayStr(), cust_id: r.cust_id, cust_name: r.cust_name, total: r.monthly_fee, status: "Unpaid", pay_terms: "Retainer", created_by: ctx.user.email, notes: `Monthly retainer — ${r.service}`, items: [{ product_id: "", product_name: `${r.service} — monthly retainer`, qty: 1, rate: r.monthly_fee, total: r.monthly_fee, notes: "" }] } }); const nx = new Date(r.next_invoice); nx.setMonth(nx.getMonth() + 1); await sbPost("upsert", { table: "retainers", label: "Retainer", row: { ...r, next_invoice: nx.toISOString().slice(0, 10) } }); } ctx.notify(`🧾 ${due.length} retainer invoice(s) generated`); await ctx.loadData(true); reload(); };
  const toggle = async r => { await sbPost("upsert", { table: "retainers", label: "Retainer", row: { ...r, status: r.status === "Active" ? "Paused" : "Active" } }); reload(); };
  const save = async () => { if (!f.cust_id || !validNum(f.monthly_fee) || +f.monthly_fee <= 0) return ctx.notify("Select client and fee", "err"); await sbPost("upsert", { table: "retainers", prefix: "RET", label: "Retainer", row: { ...f, monthly_fee: +f.monthly_fee, cust_name: ctx.custMap[f.cust_id]?.name, start: todayStr(), next_invoice: todayStr(), status: "Active" } }); ctx.notify("✅ Retainer added"); setAdd(false); reload(); };
  return (
    <div>
      <Toolbar><div style={{ flex: 1 }} /><Btn sm v="success" disabled={!due.length} onClick={generate}>🧾 Generate {due.length} due invoice(s)</Btn><Btn sm onClick={() => setAdd(true)}>+ New Retainer</Btn></Toolbar>
      <Grid cols={4}><Stat l="Monthly Recurring Revenue" v={fmt(mrr)} c={G.mid} /><Stat l="Annualised" v={fmt(mrr * 12)} c={G.blue} /><Stat l="Active Retainers" v={rows.filter(r => r.status === "Active").length} /><Stat l="Invoices Due (7 days)" v={due.length} c={G.amber} sub={fmt(due.reduce((s, r) => s + r.monthly_fee, 0))} /></Grid>
      <Card title="Retainer Agreements"><TblWrap compact heads={["ID", "Client", "Service", "Monthly Fee", "Hours Incl.", "Since", "Next Invoice", "Status", "Action"]} rows={rows.map(r => [<b style={{ fontSize: 11 }}>{r.id}</b>, <span style={{ fontSize: 11, fontWeight: 600 }}>{r.cust_name}</span>, <span style={{ fontSize: 11 }}>{r.service}</span>, <b style={{ fontSize: 11 }}>{fmt(r.monthly_fee)}</b>, <span style={{ fontSize: 11 }}>{r.hours_included || "Unlimited"}</span>, <span style={{ fontSize: 10, color: G.muted }}>{r.start}</span>, <span style={{ fontSize: 10, fontWeight: 700, color: r.next_invoice <= todayStr() ? G.red : G.muted }}>{r.next_invoice}</span>, <SPill s={r.status} />, <Btn sm v={r.status === "Active" ? "amber" : "success"} onClick={() => toggle(r)}>{r.status === "Active" ? "Pause" : "Resume"}</Btn>])} /></Card>
      {add && <Modal title="🔁 New Retainer" onClose={() => setAdd(false)}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><Sel label="Client" value={f.cust_id} onChange={e => setF(p => ({ ...p, cust_id: e.target.value }))}><option value="">— Select —</option>{ctx.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Sel><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Sel label="Service" value={f.service} onChange={e => setF(p => ({ ...p, service: e.target.value }))}>{["SEO Retainer", "Bookkeeping", "Social Media Mgmt", "Call Center 3 Seats", "Paid Ads Mgmt", "IT Support", "Consulting"].map(s => <option key={s}>{s}</option>)}</Sel><Inp label="Monthly Fee" type="number" value={f.monthly_fee} onChange={e => setF(p => ({ ...p, monthly_fee: e.target.value }))} /><Inp label="Hours Included (0 = unlimited)" type="number" value={f.hours_included} onChange={e => setF(p => ({ ...p, hours_included: +e.target.value }))} /></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Save</Btn></div></div></Modal>}
    </div>
  );
};

const StaffPage = ({ ctx }) => {
  const [ts] = useTable("timesheets", [ctx.dataVersion]); const [projects] = useTable("projects", [ctx.dataVersion]);
  const months = lastMonths(6);
  const rows = STAFF.map((s, i) => { const t = ts.filter(r => r.staff === s); const h = t.reduce((a, r) => a + r.hours, 0); const b = t.filter(r => r.billable).reduce((a, r) => a + r.hours, 0); return { s, role: ["Senior Developer", "Account Manager", "Designer", "Developer", "Bookkeeper", "Call Center Lead"][i], cost: [250000, 180000, 160000, 150000, 120000, 140000][i], h, b, rev: b * 3500, projects: projects.filter(p => p.manager === s).length }; });
  const series = [{ label: "Billable revenue", color: G.mid, values: months.map(k => ({ k, v: ts.filter(r => r.billable && monthKey(r.date) === k).reduce((a, r) => a + r.hours * r.rate, 0) })) }, { label: "Payroll cost", color: G.red, values: months.map(k => ({ k, v: rows.reduce((a, r) => a + r.cost, 0) * (k === months[months.length - 1] ? 1 : 1) })) }];
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <Grid cols={4} mb={0}><Stat l="Team" v={rows.length} /><Stat l="Avg Utilisation (30d)" v={`${Math.round(rows.reduce((a, r) => a + r.b, 0) / Math.max(1, rows.length * 160) * 100)}%`} c={G.blue} /><Stat l="Billable Value (30d)" v={fmt(rows.reduce((a, r) => a + r.rev, 0))} c={G.mid} /><Stat l="Monthly Payroll" v={fmt(rows.reduce((a, r) => a + r.cost, 0))} c={G.red} /></Grid>
      <Card title="Staff Utilisation (last 30 days, 160h capacity)"><TblWrap compact heads={["Staff", "Role", "Projects Managed", "Hours", "Billable", "Utilisation", "Billable Value", "Cost", "Margin"]} rows={rows.map(r => [<b style={{ fontSize: 11 }}>{r.s}</b>, <span style={{ fontSize: 10, color: G.muted }}>{r.role}</span>, <span style={{ fontSize: 11 }}>{r.projects}</span>, <span style={{ fontSize: 11 }}>{r.h}h</span>, <span style={{ fontSize: 11, color: G.mid }}>{r.b}h</span>, <div style={{ minWidth: 90 }}><div style={{ height: 7, background: G.pale, borderRadius: 4 }}><div style={{ height: "100%", width: `${Math.min(100, r.b / 160 * 100)}%`, background: r.b / 160 > 0.75 ? G.mid : G.amber, borderRadius: 4 }} /></div><div style={{ fontSize: 9, color: G.muted }}>{Math.round(r.b / 160 * 100)}%</div></div>, <b style={{ fontSize: 11 }}>{fmt(r.rev)}</b>, <span style={{ fontSize: 11, color: G.red }}>{fmt(r.cost)}</span>, <b style={{ fontSize: 11, color: r.rev - r.cost >= 0 ? G.mid : G.red }}>{fmt(r.rev - r.cost)}</b>])} /></Card>
      <Card title="Billable Revenue vs Payroll" color={G.blue}><div style={{ padding: 16 }}><Bars series={series} /></div></Card>
    </div>
  );
};

const DashboardExtra = ({ ctx }) => {
  const [p] = useTable("projects", [ctx.dataVersion]); const [ts] = useTable("timesheets", [ctx.dataVersion]); const [rt] = useTable("retainers", [ctx.dataVersion]);
  const unb = ts.filter(t => t.billable && !t.invoiced);
  return <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 12 }}><Kpi label="Active Projects" value={p.filter(x => x.status === "In Progress").length} sub={`${p.filter(x => x.status !== "Completed" && x.due < todayStr()).length} overdue`} color={G.blue} icon={FolderKanban} /><Kpi label="Unbilled Hours" value={`${unb.reduce((s, t) => s + t.hours, 0)}h`} sub={fmt(unb.reduce((s, t) => s + t.hours * t.rate, 0))} color={G.amber} icon={Timer} /><Kpi label="Retainer MRR" value={fmt(rt.filter(r => r.status === "Active").reduce((s, r) => s + r.monthly_fee, 0))} color={G.mid} icon={Repeat} /><Kpi label="Team Utilisation" value={`${Math.round(ts.filter(t => t.billable).reduce((s, t) => s + t.hours, 0) / (STAFF.length * 160) * 100)}%`} color={G.purple} icon={Users} /></div>;
};

export const SERVICES = {
  navGroups: [{ group: "Service Delivery", items: [{ id: "projects", label: "Projects & Jobs" }, { id: "timesheets", label: "Timesheets" }, { id: "retainers", label: "Retainers" }, { id: "staff", label: "Staff Utilisation" }] }],
  pages: { projects: ProjectsPage, timesheets: TimesheetsPage, retainers: RetainersPage, staff: StaffPage },
  DashboardExtra,
};
