// Wholesale edition: quotations, sales orders, price lists, credit control.
import { useState } from "react";
import { G, Inp, Sel, Btn, Kpi, Modal, TblWrap, todayStr, validNum } from "../apt/AptCrm.jsx";
import { Card, Stat, Grid, Toolbar, Search, Pill, SPill, useTable } from "./shared.jsx";
import { sbPost } from "../data/mockApi.js";
import { CONFIG, fmt } from "../lib/config.js";
import { openPrintable } from "../lib/invoiceDoc.js";
import { Quote, PackageCheck, ShieldAlert, Tags } from "lucide-react";

const SO_FLOW = { Confirmed: "Picking", Picking: "Dispatched", Dispatched: "Delivered", Delivered: "Invoiced" };

// Reusable line-item editor used by quotes and sales orders
const LinesEditor = ({ ctx, items, setItems }) => {
  const set = (i, k, v) => setItems(p => { const n = [...p]; n[i] = { ...n[i], [k]: v }; if (k === "product_id") { const pr = ctx.prodMap[v]; if (pr) { n[i].rate = pr.tradePrice; n[i].product_name = pr.name; } } return n; });
  return <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
    {items.map((it, i) => <div key={i} style={{ display: "grid", gridTemplateColumns: "2fr 0.7fr 1fr 1fr auto", gap: 8, alignItems: "end" }}><Sel value={it.product_id} onChange={e => set(i, "product_id", e.target.value)}><option value="">— Product —</option>{ctx.products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Sel><Inp type="number" value={it.qty} onChange={e => set(i, "qty", e.target.value)} placeholder="Qty" /><Inp type="number" value={it.rate} onChange={e => set(i, "rate", e.target.value)} placeholder="Rate" /><div style={{ background: G.pale, borderRadius: 8, padding: "8px 10px", fontSize: 12, fontWeight: 700 }}>{fmt((+it.qty || 0) * (+it.rate || 0))}</div><button onClick={() => setItems(p => p.filter((_, j) => j !== i))} style={{ background: G.pink, border: "none", borderRadius: 7, padding: "8px 9px", cursor: "pointer", color: G.red, fontWeight: 800 }}>✕</button></div>)}
    <div><Btn sm v="ghost" onClick={() => setItems(p => [...p, { product_id: "", product_name: "", qty: 10, rate: 0 }])}>+ Line</Btn></div>
  </div>;
};
const docHtml = (title, d, extra = "") => `<p><b>${d.cust_name}</b> · Date ${d.date}${d.valid_until ? ` · Valid until ${d.valid_until}` : ""}${d.delivery_date ? ` · Delivery ${d.delivery_date}` : ""}</p><table><tr><th>Item</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr>${d.items.map(i => `<tr><td>${i.product_name}</td><td class="r">${i.qty}</td><td class="r">${fmt(i.rate)}</td><td class="r">${fmt(i.qty * i.rate)}</td></tr>`).join("")}<tr><td colspan="3"><b>Total</b></td><td class="r"><b>${fmt(d.total)}</b></td></tr></table>${extra}`;

const QuotesPage = ({ ctx }) => {
  const [rows, reload] = useTable("quotes", [ctx.dataVersion]); const [q, setQ] = useState(""); const [add, setAdd] = useState(false); const [view, setView] = useState(null);
  const [f, setF] = useState({ cust_id: "", date: todayStr(), valid_until: new Date(Date.now() + 14 * 864e5).toISOString().slice(0, 10), notes: "" }); const [items, setItems] = useState([{ product_id: "", product_name: "", qty: 10, rate: 0 }]);
  const fil = rows.filter(r => !q || `${r.id} ${r.cust_name}`.toLowerCase().includes(q.toLowerCase()));
  const total = items.reduce((s, i) => s + (+i.qty || 0) * (+i.rate || 0), 0);
  const save = async () => { if (!f.cust_id || items.some(i => !i.product_id)) return ctx.notify("Select buyer and products", "err"); const c = ctx.custMap[f.cust_id]; await sbPost("upsert", { table: "quotes", prefix: "QT", label: "Quotation", row: { ...f, cust_name: c?.name, items: items.map(i => ({ ...i, qty: +i.qty, rate: +i.rate })), total, status: "Draft" } }); ctx.notify("✅ Quotation saved"); setAdd(false); setItems([{ product_id: "", product_name: "", qty: 10, rate: 0 }]); reload(); };
  const setStatus = async (r, status) => { await sbPost("upsert", { table: "quotes", label: "Quotation", row: { ...r, status } }); reload(); if (view) setView({ ...r, status }); };
  const convert = async r => { await sbPost("upsert", { table: "sales_orders", prefix: "SO", label: "Sales order", row: { date: todayStr(), cust_id: r.cust_id, cust_name: r.cust_name, total: r.total, status: "Confirmed", items: r.items, delivery_date: new Date(Date.now() + 3 * 864e5).toISOString().slice(0, 10), godown: "Godown A (Jodia)", quote_id: r.id } }); await setStatus(r, "Accepted"); ctx.notify(`✅ ${r.id} converted to sales order`); setView(null); ctx.setTab("sales-orders"); };
  const byS = s => rows.filter(r => r.status === s);
  return (
    <div>
      <Toolbar><Search value={q} onChange={setQ} placeholder="Search quotations…" /><Btn sm onClick={() => setAdd(true)}>+ New Quotation</Btn><Btn sm v="secondary" onClick={() => ctx.exportCsv("quotes.csv", rows, [["id", "Quote"], ["date", "Date"], ["cust_name", "Buyer"], ["total", "Total"], ["status", "Status"], ["valid_until", "Valid Until"]])}>⬇ Export</Btn></Toolbar>
      <Grid cols={4}><Stat l="Open Quotes" v={byS("Sent").length + byS("Draft").length} c={G.blue} sub={fmt([...byS("Sent"), ...byS("Draft")].reduce((s, r) => s + r.total, 0))} /><Stat l="Accepted" v={byS("Accepted").length} c={G.mid} sub={fmt(byS("Accepted").reduce((s, r) => s + r.total, 0))} /><Stat l="Win Rate" v={`${Math.round(byS("Accepted").length / Math.max(1, byS("Accepted").length + byS("Rejected").length + byS("Expired").length) * 100)}%`} c={G.amber} /><Stat l="Expired / Rejected" v={byS("Expired").length + byS("Rejected").length} c={G.red} /></Grid>
      <Card title="Quotations"><TblWrap compact heads={["Quote", "Date", "Buyer", "Items", "Total", "Valid Until", "Status", "Actions"]} rows={fil.map(r => [<b style={{ fontSize: 11, color: G.dark }}>{r.id}</b>, <span style={{ fontSize: 10, color: G.muted }}>{r.date}</span>, <span style={{ fontSize: 11, fontWeight: 600 }}>{r.cust_name}</span>, <span style={{ fontSize: 11 }}>{r.items.length}</span>, <b style={{ fontSize: 11 }}>{fmt(r.total)}</b>, <span style={{ fontSize: 10, color: r.valid_until < todayStr() && ["Sent", "Draft"].includes(r.status) ? G.red : G.muted }}>{r.valid_until}</span>, <SPill s={r.status} />, <div style={{ display: "flex", gap: 4 }}><Btn sm v="ghost" onClick={() => setView(r)}>View</Btn>{r.status === "Draft" && <Btn sm v="secondary" onClick={() => setStatus(r, "Sent")}>Send</Btn>}{r.status === "Sent" && <Btn sm v="success" onClick={() => convert(r)}>→ Order</Btn>}</div>])} /></Card>
      {view && <Modal title={`📄 ${view.id} — ${view.cust_name}`} onClose={() => setView(null)} wide><TblWrap compact heads={["Item", "Qty", "Rate", "Amount"]} rows={view.items.map(i => [<span style={{ fontSize: 11 }}>{i.product_name}</span>, <span style={{ fontSize: 11 }}>{i.qty}</span>, <span style={{ fontSize: 11 }}>{fmt(i.rate)}</span>, <b style={{ fontSize: 11 }}>{fmt(i.qty * i.rate)}</b>])} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}><b style={{ fontSize: 15 }}>Total {fmt(view.total)}</b><div style={{ display: "flex", gap: 8 }}><Btn v="secondary" onClick={() => openPrintable(`Quotation ${view.id}`, docHtml("Quotation", view, "<p class='muted'>Prices valid until the date shown. Subject to stock availability.</p>"))}>🖨 Print</Btn>{["Sent", "Draft"].includes(view.status) && <Btn v="danger" onClick={() => setStatus(view, "Rejected")}>Mark Lost</Btn>}{["Sent", "Draft"].includes(view.status) && <Btn v="success" onClick={() => convert(view)}>✓ Accept → Sales Order</Btn>}</div></div></Modal>}
      {add && <Modal title="📝 New Quotation" onClose={() => setAdd(false)} wide><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><div style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr", gap: 10 }}><Sel label="Buyer" value={f.cust_id} onChange={e => setF(p => ({ ...p, cust_id: e.target.value }))}><option value="">— Select —</option>{ctx.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Sel><Inp label="Date" type="date" value={f.date} onChange={e => setF(p => ({ ...p, date: e.target.value }))} /><Inp label="Valid Until" type="date" value={f.valid_until} onChange={e => setF(p => ({ ...p, valid_until: e.target.value }))} /></div><LinesEditor ctx={ctx} items={items} setItems={setItems} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><b style={{ fontSize: 15 }}>Total {fmt(total)}</b><div style={{ display: "flex", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Save Quotation</Btn></div></div></div></Modal>}
    </div>
  );
};

const SalesOrdersPage = ({ ctx }) => {
  const [rows, reload] = useTable("sales_orders", [ctx.dataVersion]); const [q, setQ] = useState(""); const [st, setSt] = useState("All"); const [add, setAdd] = useState(false); const [view, setView] = useState(null);
  const [f, setF] = useState({ cust_id: "", date: todayStr(), delivery_date: new Date(Date.now() + 3 * 864e5).toISOString().slice(0, 10), godown: "Godown A (Jodia)" }); const [items, setItems] = useState([{ product_id: "", product_name: "", qty: 10, rate: 0 }]);
  const fil = rows.filter(r => (st === "All" || r.status === st) && (!q || `${r.id} ${r.cust_name}`.toLowerCase().includes(q.toLowerCase())));
  const total = items.reduce((s, i) => s + (+i.qty || 0) * (+i.rate || 0), 0);
  const creditOk = cid => { const c = ctx.custMap[cid]; const bal = ctx.ar.find(r => r.custId === cid)?.balance || 0; return !c?.credit_limit || bal + total <= c.credit_limit; };
  const save = async () => { if (!f.cust_id || items.some(i => !i.product_id)) return ctx.notify("Select buyer and products", "err"); if (!creditOk(f.cust_id)) { if (!confirm("This order exceeds the buyer's credit limit. Create anyway (requires approval)?")) return; } const c = ctx.custMap[f.cust_id]; await sbPost("upsert", { table: "sales_orders", prefix: "SO", label: "Sales order", row: { ...f, cust_name: c?.name, items: items.map(i => ({ ...i, qty: +i.qty, rate: +i.rate })), total, status: "Confirmed" } }); ctx.notify("✅ Sales order created"); setAdd(false); reload(); };
  const advance = async r => {
    const next = SO_FLOW[r.status]; if (!next) return;
    if (next === "Invoiced") {
      const id = `INV-${String(Math.max(1000, ...ctx.invoices.map(i => parseInt((i.id.match(/INV-(\d+)/) || [])[1] || 0))) + 1).padStart(4, "0")}`;
      await sbPost("upsert_invoice", { invoice: { id, date: todayStr(), cust_id: r.cust_id, cust_name: r.cust_name, total: r.total, status: "Unpaid", pay_terms: "NET 15", created_by: ctx.user.email, notes: `From ${r.id}`, items: r.items.map(i => ({ product_id: i.product_id, product_name: i.product_name, qty: i.qty, rate: i.rate, total: i.qty * i.rate, notes: "" })) } });
      await sbPost("upsert", { table: "sales_orders", label: "Sales order", row: { ...r, status: "Invoiced", invoice_id: id } }); ctx.notify(`🧾 ${id} created from ${r.id}`); await ctx.loadData(true);
    } else { if (next === "Dispatched") for (const i of r.items) await sbPost("adjust_stock", { pid: i.product_id, delta: -i.qty }); await sbPost("upsert", { table: "sales_orders", label: "Sales order", row: { ...r, status: next } }); ctx.notify(`✅ ${r.id} → ${next}`); if (next === "Dispatched") ctx.loadData(true); }
    reload(); setView(null);
  };
  const open = rows.filter(r => !["Invoiced", "Delivered"].includes(r.status));
  return (
    <div>
      <Toolbar><Search value={q} onChange={setQ} placeholder="Search orders…" />{["All", "Confirmed", "Picking", "Dispatched", "Delivered", "Invoiced"].map(s => <button key={s} onClick={() => setSt(s)} style={{ padding: "5px 11px", borderRadius: 20, border: `1.5px solid ${st === s ? G.dark : G.border}`, background: st === s ? G.dark : G.bg, color: st === s ? G.white : G.ink, fontSize: 10, fontWeight: 700, cursor: "pointer" }}>{s}</button>)}<Btn sm onClick={() => setAdd(true)}>+ New Order</Btn></Toolbar>
      <Grid cols={4}><Stat l="Open Orders" v={open.length} c={G.blue} sub={fmt(open.reduce((s, r) => s + r.total, 0))} /><Stat l="To Pick Today" v={rows.filter(r => r.status === "Confirmed").length} c={G.amber} /><Stat l="Dispatched (awaiting POD)" v={rows.filter(r => r.status === "Dispatched").length} c={G.purple} /><Stat l="Delivered, not invoiced" v={rows.filter(r => r.status === "Delivered").length} c={G.red} /></Grid>
      <Card title="Sales Orders"><TblWrap compact heads={["Order", "Date", "Buyer", "Godown", "Total", "Delivery", "Status", "Actions"]} rows={fil.map(r => [<b style={{ fontSize: 11, color: G.dark }}>{r.id}</b>, <span style={{ fontSize: 10, color: G.muted }}>{r.date}</span>, <span style={{ fontSize: 11, fontWeight: 600 }}>{r.cust_name}</span>, <span style={{ fontSize: 10 }}>{r.godown}</span>, <b style={{ fontSize: 11 }}>{fmt(r.total)}</b>, <span style={{ fontSize: 10, color: G.muted }}>{r.delivery_date}</span>, <SPill s={r.status} />, <div style={{ display: "flex", gap: 4 }}><Btn sm v="ghost" onClick={() => setView(r)}>View</Btn>{SO_FLOW[r.status] && <Btn sm v="success" onClick={() => advance(r)}>→ {SO_FLOW[r.status]}</Btn>}{r.invoice_id && <Pill text={r.invoice_id} color={G.mid} bg={G.pale} />}</div>])} /></Card>
      {view && <Modal title={`📦 ${view.id} — ${view.cust_name}`} onClose={() => setView(null)} wide><TblWrap compact heads={["Item", "Qty", "Rate", "Amount", "In Stock"]} rows={view.items.map(i => [<span style={{ fontSize: 11 }}>{i.product_name}</span>, <span style={{ fontSize: 11 }}>{i.qty}</span>, <span style={{ fontSize: 11 }}>{fmt(i.rate)}</span>, <b style={{ fontSize: 11 }}>{fmt(i.qty * i.rate)}</b>, <span style={{ fontSize: 11, color: (ctx.prodMap[i.product_id]?.currentStock || 0) < i.qty ? G.red : G.mid, fontWeight: 700 }}>{ctx.prodMap[i.product_id]?.currentStock ?? "—"}</span>])} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}><b style={{ fontSize: 15 }}>Total {fmt(view.total)}</b><div style={{ display: "flex", gap: 8 }}><Btn v="secondary" onClick={() => openPrintable(`${view.status === "Confirmed" ? "Pick List" : "Delivery Challan"} ${view.id}`, docHtml("Order", view, `<p class='muted'>Godown: ${view.godown} · Received by: ____________________  Signature: ____________</p>`))}>🖨 {view.status === "Confirmed" ? "Pick List" : "Delivery Challan"}</Btn>{SO_FLOW[view.status] && <Btn v="success" onClick={() => advance(view)}>→ {SO_FLOW[view.status]}</Btn>}</div></div></Modal>}
      {add && <Modal title="📦 New Sales Order" onClose={() => setAdd(false)} wide><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><div style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr", gap: 10 }}><Sel label="Buyer" value={f.cust_id} onChange={e => setF(p => ({ ...p, cust_id: e.target.value }))}><option value="">— Select —</option>{ctx.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Sel><Inp label="Order Date" type="date" value={f.date} onChange={e => setF(p => ({ ...p, date: e.target.value }))} /><Inp label="Delivery" type="date" value={f.delivery_date} onChange={e => setF(p => ({ ...p, delivery_date: e.target.value }))} /><Sel label="Godown" value={f.godown} onChange={e => setF(p => ({ ...p, godown: e.target.value }))}><option>Godown A (Jodia)</option><option>Godown B (SITE)</option></Sel></div>{f.cust_id && <div style={{ background: creditOk(f.cust_id) ? G.pale : G.pink, borderRadius: 8, padding: "8px 12px", fontSize: 11, fontWeight: 700, color: creditOk(f.cust_id) ? G.mid : G.red }}>Credit limit {fmt(ctx.custMap[f.cust_id]?.credit_limit)} · outstanding {fmt(ctx.ar.find(r => r.custId === f.cust_id)?.balance || 0)} · this order {fmt(total)} {creditOk(f.cust_id) ? "✓ within limit" : "⚠ exceeds limit — approval needed"}</div>}<LinesEditor ctx={ctx} items={items} setItems={setItems} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><b style={{ fontSize: 15 }}>Total {fmt(total)}</b><div style={{ display: "flex", gap: 8 }}><Btn v="secondary" onClick={() => setAdd(false)}>Cancel</Btn><Btn onClick={save}>💾 Confirm Order</Btn></div></div></div></Modal>}
    </div>
  );
};

const PriceListsPage = ({ ctx }) => {
  const [lists, reload] = useTable("price_lists", [ctx.dataVersion]); const [edit, setEdit] = useState({});
  const save = async l => { const v = Number(edit[l.id]); if (isNaN(v)) return; await sbPost("upsert", { table: "price_lists", label: "Price list", row: { ...l, markup: v } }); ctx.notify(`✅ ${l.name} markup set to ${v}%`); setEdit(p => ({ ...p, [l.id]: "" })); reload(); };
  const print = () => openPrintable("Price List", `<table><tr><th>Product</th><th class="r">Base</th>${lists.map(l => `<th class="r">${l.name}</th>`).join("")}</tr>${ctx.products.map(p => `<tr><td>${p.name}</td><td class="r">${fmt(p.tradePrice)}</td>${lists.map(l => `<td class="r">${fmt(p.tradePrice * (1 + l.markup / 100))}</td>`).join("")}</tr>`).join("")}</table>`);
  return (
    <div>
      <Toolbar><div style={{ flex: 1 }} /><Btn sm onClick={print}>🖨 Print Price List</Btn></Toolbar>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 12, marginBottom: 14 }}>{lists.map(l => <div key={l.id} style={{ background: G.card, borderRadius: 11, padding: 14, boxShadow: "0 2px 10px rgba(15,59,76,0.07)", borderTop: `3px solid ${G.purple}` }}><div style={{ fontWeight: 800, fontSize: 13 }}>{l.name}</div><div style={{ fontSize: 22, fontWeight: 800, color: G.dark, margin: "4px 0" }}>+{l.markup}%</div><div style={{ display: "flex", gap: 6 }}><input value={edit[l.id] || ""} onChange={e => setEdit(p => ({ ...p, [l.id]: e.target.value }))} placeholder="new %" style={{ width: 70, border: `1px solid ${G.border}`, borderRadius: 6, padding: "4px 6px", fontSize: 11 }} /><Btn sm onClick={() => save(l)}>Set</Btn></div></div>)}</div>
      <Card title="Price Matrix (base = trade price)"><TblWrap compact heads={["Product", "Category", "Cost", "Base", ...lists.map(l => l.name), "Stock"]} rows={ctx.products.map(p => [<span style={{ fontSize: 11, fontWeight: 600 }}>{p.name}</span>, <Pill text={p.category} />, <span style={{ fontSize: 10, color: G.muted }}>{fmt(p.tradePrice * 0.78)}</span>, <b style={{ fontSize: 11 }}>{fmt(p.tradePrice)}</b>, ...lists.map(l => <span key={l.id} style={{ fontSize: 11, color: G.dark }}>{fmt(p.tradePrice * (1 + l.markup / 100))}</span>), <span style={{ fontSize: 11, color: p.currentStock <= 0 ? G.red : G.ink }}>{p.currentStock}</span>])} /></Card>
    </div>
  );
};

const CreditPage = ({ ctx }) => {
  const [edit, setEdit] = useState({});
  const rows = ctx.customers.map(c => { const bal = ctx.ar.find(r => r.custId === c.id)?.balance || 0; const lim = c.credit_limit || 0; const oldest = ctx.invoices.filter(i => i.custId === c.id && (i.status === "Unpaid" || i.status === "Partial")).map(i => Math.floor((Date.now() - new Date(i.date)) / 864e5)); return { ...c, bal, lim, util: lim ? bal / lim : 0, oldest: oldest.length ? Math.max(...oldest) : 0 }; }).sort((a, b) => b.util - a.util);
  const over = rows.filter(r => r.util > 1), near = rows.filter(r => r.util > 0.8 && r.util <= 1);
  const setLimit = async c => { const v = Number(edit[c.id]); if (!v) return; await sbPost("upsert_customer", { customer: { id: c.id, credit_limit: v } }); ctx.notify(`✅ ${c.name} limit → ${fmt(v)}`); setEdit(p => ({ ...p, [c.id]: "" })); ctx.loadData(true); };
  const toggleHold = async c => { await sbPost("upsert_customer", { customer: { id: c.id, on_hold: !c.on_hold } }); ctx.notify(c.on_hold ? `✅ ${c.name} released` : `⛔ ${c.name} put on credit hold`); ctx.loadData(true); };
  return (
    <div>
      <Grid cols={4}><Stat l="Total Credit Extended" v={fmt(rows.reduce((s, r) => s + r.lim, 0))} /><Stat l="Credit Used" v={fmt(rows.reduce((s, r) => s + Math.max(0, r.bal), 0))} c={G.amber} /><Stat l="Over Limit" v={over.length} c={G.red} sub={fmt(over.reduce((s, r) => s + r.bal - r.lim, 0)) + " excess"} /><Stat l="Near Limit (>80%)" v={near.length} c={G.purple} /></Grid>
      <Card title="Credit Control"><TblWrap compact heads={["Buyer", "Category", "Limit", "Outstanding", "Utilisation", "Oldest Due", "Status", "Set Limit", "Action"]} rows={rows.map(r => [<div><b style={{ fontSize: 11 }}>{r.name}</b><div style={{ fontSize: 9, color: G.muted }}>{r.area} · {r.city}</div></div>, <Pill text={`Class ${r.category || "B"}`} />, <span style={{ fontSize: 11 }}>{fmt(r.lim)}</span>, <b style={{ fontSize: 11, color: r.bal > 0 ? G.red : G.mid }}>{fmt(r.bal)}</b>, <div style={{ minWidth: 90 }}><div style={{ height: 7, background: G.pale, borderRadius: 4 }}><div style={{ height: "100%", width: `${Math.min(100, r.util * 100)}%`, background: r.util > 1 ? G.red : r.util > 0.8 ? G.amber : G.mid, borderRadius: 4 }} /></div><div style={{ fontSize: 9, color: G.muted }}>{Math.round(r.util * 100)}%</div></div>, <span style={{ fontSize: 10, fontWeight: 700, color: r.oldest > 45 ? G.red : G.muted }}>{r.oldest ? `${r.oldest}d` : "—"}</span>, r.on_hold ? <Pill text="ON HOLD" color={G.red} bg={G.pink} /> : r.util > 1 ? <Pill text="Over limit" color={G.red} bg={G.pink} /> : <Pill text="OK" color={G.mid} bg={G.pale} />, <div style={{ display: "flex", gap: 4 }}><input value={edit[r.id] || ""} onChange={e => setEdit(p => ({ ...p, [r.id]: e.target.value }))} placeholder={String(r.lim)} style={{ width: 80, border: `1px solid ${G.border}`, borderRadius: 6, padding: "4px 6px", fontSize: 11 }} /><Btn sm onClick={() => setLimit(r)}>Set</Btn></div>, <div style={{ display: "flex", gap: 4 }}><Btn sm v={r.on_hold ? "success" : "danger"} onClick={() => toggleHold(r)}>{r.on_hold ? "Release" : "Hold"}</Btn>{r.bal > 0 && <Btn sm v="secondary" onClick={() => ctx.setModal({ t: "recordPayment", d: { custId: r.id } })}>Collect</Btn>}</div>])} /></Card>
    </div>
  );
};

const DashboardExtra = ({ ctx }) => {
  const [so] = useTable("sales_orders", [ctx.dataVersion]); const [qt] = useTable("quotes", [ctx.dataVersion]);
  const open = so.filter(r => !["Invoiced", "Delivered"].includes(r.status)); const over = ctx.customers.filter(c => c.credit_limit && (ctx.ar.find(r => r.custId === c.id)?.balance || 0) > c.credit_limit).length;
  return <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 12 }}><Kpi label="Open Sales Orders" value={open.length} sub={fmt(open.reduce((s, r) => s + r.total, 0))} color={G.blue} icon={PackageCheck} /><Kpi label="Quotes Awaiting Reply" value={qt.filter(q => q.status === "Sent").length} sub={fmt(qt.filter(q => q.status === "Sent").reduce((s, r) => s + r.total, 0))} color={G.purple} icon={Quote} /><Kpi label="Buyers Over Credit Limit" value={over} color={over ? G.red : G.mid} icon={ShieldAlert} /><Kpi label="Avg Order Value" value={fmt(so.length ? so.reduce((s, r) => s + r.total, 0) / so.length : 0)} color={G.amber} icon={Tags} /></div>;
};

export const WHOLESALE = {
  navGroups: [{ group: "Trading", items: [{ id: "quotes", label: "Quotations" }, { id: "sales-orders", label: "Sales Orders" }, { id: "price-lists", label: "Price Lists" }, { id: "credit", label: "Credit Control" }] }],
  pages: { quotes: QuotesPage, "sales-orders": SalesOrdersPage, "price-lists": PriceListsPage, credit: CreditPage },
  DashboardExtra,
};
